# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                submodules: 'true'
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: Install
              working-directory: ./Code/react-src
              run: |
                npm install --frozen-lockfile
            - name: Test React
              working-directory: ./Code/react-src
              run: npm run test
            - name: Build React
              working-directory: ./Code/react-src
              run: npm run build --if-present
