# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node and React CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: 'true'
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: Shutdown Ubuntu MySQL (SUDO)
              run: sudo service mysql stop
            - name: Create Database
              uses: getong/mariadb-action@v1.1
              with:
                  host port: 3306
                  container port: 3306
                  character set server: 'utf8mb4'
                  collation server: 'utf8mb4_general_ci'
                  mariadb version: 'latest'
                  mysql database: 'cosc499'
                  mysql root password: password
            - name: Install node-src
              working-directory: ./Code/node-src
              run: |
                npm install --frozen-lockfile
            - name: Test node-src
              working-directory: ./Code/node-src
              run: npm run test
            - name: Build node-src
              working-directory: ./Code/node-src
              run: npm run build --if-present
            - name: Install react-src
              working-directory: ./Code/react-src
              run: |
                npm install --frozen-lockfile
            - name: Test react-src
              working-directory: ./Code/react-src
              run: npm run test
            - name: Build react-src
              working-directory: ./Code/react-src
              run: npm run build --if-present
